import { jsPDF } from 'jspdf';
import { getZorPdfFileName } from './fileNaming';

export interface DocxToPdfResult {
  blob: Blob;
  filename: string;
}

export async function convertDocxToPdf(docxFile: File): Promise<DocxToPdfResult> {
  try {
    // Import mammoth dynamically
    const mammoth = await import('mammoth');

    // Read DOCX file
    const arrayBuffer = await docxFile.arrayBuffer();

    // Convert DOCX to HTML
    const result = await mammoth.convertToHtml({ arrayBuffer });
    const html = result.value;

    if (!html || html.trim().length === 0) {
      throw new Error('No content found in DOCX file');
    }

    // Create temporary container to measure text
    const container = document.createElement('div');
    container.style.position = 'absolute';
    container.style.left = '-9999px';
    container.style.top = '-9999px';
    container.style.width = '190mm';
    container.style.fontFamily = 'Arial, sans-serif';
    container.style.fontSize = '12px';
    container.style.lineHeight = '1.5';
    container.innerHTML = html;
    document.body.appendChild(container);

    // Create PDF
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const margin = 10;
    const contentWidth = pageWidth - 2 * margin;

    // Get text from HTML and split into lines
    const text = container.innerText || container.textContent || '';
    const lines = text.split('\n').filter(line => line.trim().length > 0);

    if (lines.length === 0) {
      throw new Error('No text content could be extracted from DOCX');
    }

    pdf.setFontSize(11);
    let yPosition = margin + 5;
    const lineHeight = 7;

    for (const line of lines) {
      const wrappedLines = pdf.splitTextToSize(line, contentWidth);

      for (const wrappedLine of wrappedLines) {
        if (yPosition + lineHeight > pageHeight - margin) {
          pdf.addPage();
          yPosition = margin + 5;
        }

        pdf.text(wrappedLine, margin, yPosition);
        yPosition += lineHeight;
      }
    }

    // Add footer branding
    pdf.setFontSize(8);
    pdf.setTextColor(150, 150, 150);
    pdf.text('Generated by zorPDF.com', margin, pageHeight - 5);

    // Create blob
    const pdfBlob = pdf.output('blob');
    const filename = getZorPdfFileName('pdf');

    // Cleanup
    document.body.removeChild(container);

    return {
      blob: pdfBlob,
      filename,
    };
  } catch (err) {
    throw new Error(`Failed to convert DOCX to PDF: ${err instanceof Error ? err.message : 'Unknown error'}`);
  }
}
